### ISSUE TITLE
请教一下，如果一个界面拖好之后，那怎么访问这个界面呢？

### ISSUE THREAD

**Issue by kyan54** [mrabit/vue-formbuilder#8]
请教一下，如果一个界面拖好之后，那怎么访问这个界面呢？
是存成json然后写解析器解析，还是怎么处理的？

**Comment by mrabit** [comment]
是把整个json存起来在页面解析，demo里都是有示例的  这样做的主要原因是当初项目里工作流内表单字段是不固定的，随时需要取值并且随时可能需要显示表单 所以最好的方法是存json方便解析
